### ISSUE TITLE
Vulkan version does not run.

### ISSUE THREAD

**Issue by jayrulez** [andrejnau/SponzaPbr#1]
The vulkan version does not run.

It seems shader compilation fails for RayTracingAO.hlsl

**Comment by andrejnau** [comment]
I can't reproduce it. If shader compilation failed, make sure that you are using the latest vulkan sdk.

**Comment by jayrulez** [comment]
I'm currently using 1.2.162.1. The recommended version in the readme is 1.2.162.0. I'll update to the latest and try again.

**Comment by andrejnau** [comment]
Sorry, I did not update readme for a while. Please try 1.2.176.1.

**Comment by jayrulez** [comment]
Yes, it works with 1.2.176.1.

Is there any way I can contact you with quick questions about flycube that may not be worthy of github issues?
Discord, email or anything else will do.

**Comment by andrejnau** [comment]
I will email you
